"""
Simple demo to test Gemini AI integration - Windows compatible (no emojis)
"""
import sqlite3
from datetime import datetime
import time
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from gemini_service import generate_xai_explanation, generate_knowledge_graph_data

print("="*70)
print("GEMINI AI INTEGRATION DEMO")
print("="*70)

# Test with a sample event
print("\n[TEST 1] Privilege Escalation Event")
print("-"*70)

explanation = generate_xai_explanation(
    event_type="PRIV_ESC",
    process_name="exploit.sh",
    pid=1337,
    severity="HIGH",
    details="UID transition from 1000 to 0 without execve() - potential exploit-based elevation"
)

print("\nXAI Explanation:")
print(explanation)

graph = generate_knowledge_graph_data(
    event_type="PRIV_ESC",
    process_name="exploit.sh",
    pid=1337,
    details="UID transition from 1000 to 0 without execve()"
)

print("\nKnowledge Graph:")
print(f"  Nodes: {len(graph['nodes'])}")
print(f"  Links: {len(graph['links'])}")
for node in graph['nodes']:
    print(f"  - {node['name']} ({node['type']})")

print("\n" + "="*70)
print("\n[TEST 2] Hidden Process Event")
print("-"*70)

explanation2 = generate_xai_explanation(
    event_type="HIDDEN_PROCESS",
    process_name="rootkit_daemon",
    pid=6666,
    severity="HIGH",
    details="Process visible in task_struct but missing from /proc filesystem"
)

print("\nXAI Explanation:")
print(explanation2)

graph2 = generate_knowledge_graph_data(
    event_type="HIDDEN_PROCESS",
    process_name="rootkit_daemon",
    pid=6666,
    details="Cross-view inconsistency detected"
)

print("\nKnowledge Graph:")
print(f"  Nodes: {len(graph2['nodes'])}")
for node in graph2['nodes']:
    print(f"  - {node['name']} ({node['type']})")

print("\n" + "="*70)
print("DEMO COMPLETE - Gemini AI is working!")
print("="*70)
print("\nThe XAI explanations above were generated by Gemini AI.")
print("The knowledge graphs show realistic process lineage.")
print("\nNext: Start the backend and frontend to see this in the dashboard!")
